
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carlo
 */
public class InicioProveedor extends javax.swing.JFrame {

    /**
     * Creates new form InicioProveedor
     */
    public InicioProveedor() {
        initComponents();
    }
    public static String user = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblContraseñaP = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        btnIniciarP = new javax.swing.JButton();
        btnRegistroP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("PROVEEDOR");

        lblRfc.setText("RFC");

        lblContraseñaP.setText("Contraseña");

        btnIniciarP.setText("Iniciar Sesion");
        btnIniciarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPActionPerformed(evt);
            }
        });

        btnRegistroP.setText("Registrar Proveedor");
        btnRegistroP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(lblRfc)
                        .addComponent(lblContraseñaP)
                        .addComponent(btnIniciarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRegistroP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtContra)
                        .addComponent(txtRfc))
                    .addGap(53, 53, 53)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel2)
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRfc)
                        .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblContraseñaP))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciarP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRegistroP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPActionPerformed
        // TODO add your handling code here:
        user = txtRfc.getText();
        String pwd = txtContra.getText();
        String record = null;
        FileReader in = null;
        boolean existe = false; // para comprobar si cuenta y pass no coindicen con ninguna línea
        try {
            in = new FileReader("C:\\Users\\Carlo\\OneDrive\\Escritorio\\Proveedores.txt");
            BufferedReader br = new BufferedReader(in);

            while ((record = br.readLine()) !=null) {

                String [] word = record.split(","); // dividir en palabras delimitadas por espacios
                for(int x = 0; x < word.length; x = x+9 ){
                    if (word[x+1].equals(user) && word[x+8].equals(pwd)) {
                        Proveedores acceso = new Proveedores ();
                        acceso.setVisible (true);
                        this.setVisible (false);
                        existe = true;
                    }
                }
            }

            if (!existe) {
                JOptionPane.showMessageDialog(null,"usuario o contraseña incorrectos");
            }
        } catch (IOException e) {
            e.getCause();
        }
    }//GEN-LAST:event_btnIniciarPActionPerformed

    private void btnRegistroPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPActionPerformed
        // TODO add your handling code here:
        Rproveedores acceso = new Rproveedores();
        acceso.setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistroPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarP;
    private javax.swing.JButton btnRegistroP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContraseñaP;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
