
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carlo
 */
public class Proveedores extends javax.swing.JFrame {
    String productos [] = {"Agua","Jugos","Atun","Lentejas","Frijoles","Aceites","Refrescos","Salsa","Cafe","Cigarros"};
    double precios [] = {12.9,17.9,15.0,10.0,39.9,46.5,16.0,25.0,18.9,70.0};
    double precio = 0;
    int cantidad = 0;
    ArrayList <String> fproducto = new ArrayList <String>();
    ArrayList <Integer> fcantidad = new ArrayList <Integer>();
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Venta> listaVentas = new ArrayList <Venta>();
    ArrayList <String> finventarios = new ArrayList <String>();
    public static String sub = "";
    public static String ivaa = "";
    public static String fproductos= "";
    public static String cadena = "";
    public static String ncantidad = "";
    public static String subto = "";
    public static String ivaaa = "";
    public static String product = "";
    public static String cant = "";
    public static int inventario = 0;
    String newstring;

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        this.setTitle("Abarrotes El pirata");
        DefaultComboBoxModel comboModel=new DefaultComboBoxModel(productos);
        cboProducto.setModel(comboModel);
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PRECIO U.");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("IMPORTE");
        actualizarTabla();
        calcularPrecio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblSubtotal = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        cboProducto = new javax.swing.JComboBox<>();
        btnFactu = new javax.swing.JButton();
        spnCantidad = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Precio");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Subtotal");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("IVA");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Importe");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Total");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSubtotal.setText("$0.00 MXN");

        lblImporte.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblImporte.setText("$0.00 MXN");

        lblIVA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblIVA.setText("$0.00 MXN");

        lblPrecio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPrecio.setText("$0.00 MXN");

        lblTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTotal.setText("$0.00 MXN");

        cboProducto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProductoActionPerformed(evt);
            }
        });

        btnFactu.setText("Factura");
        btnFactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactuActionPerformed(evt);
            }
        });

        spnCantidad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spnCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCantidadStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setText("Productos Abarrotes El Pirata");

        tblProductos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cboProducto, 0, 129, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImporte)
                            .addComponent(lblPrecio))
                        .addGap(28, 28, 28)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnFactu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(78, 78, 78)
                                .addComponent(lblTotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(89, 89, 89)
                                .addComponent(lblIVA))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(53, 53, 53)
                                .addComponent(lblSubtotal)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(191, 191, 191))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblPrecio)
                            .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lblImporte)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblSubtotal))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFactu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblIVA))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTotal)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Venta venta = new Venta ();
        venta.setId(cboProducto.getSelectedIndex());
        venta.setDescripcion (cboProducto.getSelectedItem().toString());
        venta.setPrecio(precio);
        venta.setCantidad(cantidad);
        venta.setImporte(precio*cantidad);
        if(!buscarVenta(venta)){
            listaVentas.add(venta);
        }      
        fproducto.add(venta.getDescripcion());
        fcantidad.add(venta.getCantidad());
        actualizarTabla();
        borrarVenta();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProductoActionPerformed
        calcularPrecio();
    }//GEN-LAST:event_cboProductoActionPerformed

    private void btnFactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactuActionPerformed
        sub = lblSubtotal.getText();
        ivaa = lblIVA.getText();
        cadena = fproducto.toString();
        ncantidad = fcantidad.toString();
        Fproveedor fact = new Fproveedor();
        fact.setVisible(true);
        this.setVisible(false);
        subto = lblSubtotal.getText();
        ivaaa = lblIVA.getText();
        product = fproducto.toString();
        cant = fcantidad.toString();
        try
        {
            String filePath = "C:\\Users\\Carlo\\OneDrive\\Escritorio\\ReporteCompra.txt";
            FileWriter fw = new FileWriter(filePath, true);    
            String subtotal = subto+",";    
            fw.write(subtotal);
            String iva = ivaaa+",";
            fw.write(iva);
            String producto = product+",";
            fw.write(producto);
            String cantidad = cant+",";
            fw.write(cantidad);
            fw.close();
            JOptionPane.showMessageDialog(null,"Se agrego al inventario");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        try
        {
            InicioProveedor a = new InicioProveedor();
            String filePath = "C:\\Users\\Carlo\\OneDrive\\Escritorio\\Facturas.txt";
            FileWriter fw = new FileWriter(filePath, true);  
            fw.write("Compra ");
            String usuario = a.user;
            fw.write(usuario);
            String subtotal = subto+",";    
            fw.write(subtotal);
            String iva = ivaaa+",";
            fw.write(iva);
            String producto = product+",";
            fw.write(producto);
            String cantidad = cant+",";
            fw.write(cantidad);
            fw.close();
            JOptionPane.showMessageDialog(null,"Se agrego la factura");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        try {
           String filePath = "C:\\Users\\Carlo\\OneDrive\\Escritorio\\ReporteGanancia.txt";
            FileWriter fw = new FileWriter(filePath, true);
            double subtotal = 0;
            for (Venta v : listaVentas){
            Object x [] = new Object [5];
            x[0] = v.getDescripcion();
            x[1] = aMoneda(v.getPrecio ());
            x[2] = v.getCantidad ();
            x[3] = v.getImporte ();
            subtotal += v.getImporte();
        }
            
            String subtota = String.valueOf(subtotal);
            fw.write("-"+subtota+ " ");  
            fw.close();
        }catch (Exception e){
             System.out.println(e);
        }
        String record = null;
        FileReader in = null;
        int ninventario = 0;
        boolean existe = false; // para comprobar si cuenta y pass no coindicen con ninguna línea 
         try {
        in = new FileReader("C:\\Users\\Carlo\\OneDrive\\Escritorio\\Inventario.txt");
        BufferedReader br = new BufferedReader(in);

        while ((record = br.readLine()) !=null) {
            
            String [] word = record.split(","); // dividir en palabras delimitadas por espacios
            for(int x = 0; x < word.length; x = x+2 ){
                for (Venta v : listaVentas){
            if (word[x].equals(v.getDescripcion())) {
                
                int ncantidad =  v.getCantidad();
                String nproducto = word[x+1];
                ninventario = Integer.parseInt(nproducto.trim());
                inventario += ninventario + ncantidad;
                word [x+1]= String.valueOf(inventario);
                newstring = Arrays.toString(word).replace("[", "").replace("]","").trim();
                inventario = 0;
            }
                }
            }
        }
        BufferedWriter bw = new BufferedWriter(new FileWriter("C:\\Users\\Carlo\\OneDrive\\Escritorio\\Inventario.txt"));
        bw.write("");
        String filePath = "C:\\Users\\Carlo\\OneDrive\\Escritorio\\Inventario.txt";
                FileWriter fw = new FileWriter(filePath, true);
                fw.write(newstring);  
                fw.close();
    } catch (IOException e) {
        e.getCause();
    } 
        
        
    }//GEN-LAST:event_btnFactuActionPerformed

    private void spnCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCantidadStateChanged
        calcularPrecio();
    }//GEN-LAST:event_spnCantidadStateChanged
public boolean buscarVenta(Venta nueva){
        for (Venta v : listaVentas){
            if(v.getId()==nueva.getId()){
                int nuevaCantidad = v.getCantidad()+nueva.getCantidad();
                v.setCantidad(nuevaCantidad); 
                v.setImporte(v.getPrecio()*nuevaCantidad);
                return true;
            }
        }
        return false;
    }
    public void borrarVenta (){
        precio = 0;
        cantidad = 1;
        cboProducto.setSelectedIndex(0);
        spnCantidad.setValue(1);
        calcularPrecio();
    }
    public void calcularPrecio (){
       precio = precios[cboProducto.getSelectedIndex()];
       cantidad = Integer.parseInt(spnCantidad.getValue().toString());
       lblPrecio.setText (aMoneda (precio));
       lblImporte.setText (aMoneda (precio*cantidad) ) ;
    }
    public String aMoneda (double precio){
        return "$ " + Math.round(precio*100.00)/100.00+"MXN";
    }
    public void actualizarTabla(){
        while (modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        double subtotal = 0;
        for (Venta v : listaVentas){
            Object x [] = new Object [5];
            x[0] = v.getDescripcion();
            x[1] = aMoneda(v.getPrecio ());
            x[2] = v.getCantidad ();
            x[3] = aMoneda(v.getImporte ());
            subtotal += v.getImporte();
            modelo.addRow(x);
        }
        double iva = subtotal *0.16;
        double total = subtotal +iva;
        lblSubtotal.setText(aMoneda(subtotal));
        lblIVA.setText(aMoneda(iva));
        lblTotal.setText(aMoneda(total));
        tblProductos.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnFactu;
    private javax.swing.JComboBox<String> cboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
