
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carlo
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        
     }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNnocliente = new javax.swing.JLabel();
        lblNrfc = new javax.swing.JLabel();
        lblNrazonsocial = new javax.swing.JLabel();
        lblNdireccionfiscal = new javax.swing.JLabel();
        lblNcontacto = new javax.swing.JLabel();
        lblNtelefono = new javax.swing.JLabel();
        lblNcontraseña = new javax.swing.JLabel();
        txtNnocliente = new javax.swing.JTextField();
        txtNrfc = new javax.swing.JTextField();
        txtNrazonsocial = new javax.swing.JTextField();
        txtNdireccionfiscal = new javax.swing.JTextField();
        txtNcontacto = new javax.swing.JTextField();
        txtNtelefono = new javax.swing.JTextField();
        txtNcontraseña = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNnocliente.setText("No. Cliente");

        lblNrfc.setText("RFC");

        lblNrazonsocial.setText("Razon Social");

        lblNdireccionfiscal.setText("Direccion Fiscal");

        lblNcontacto.setText("Nombre de contacto");

        lblNtelefono.setText("Telefono");

        lblNcontraseña.setText("Contraseña");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRO CLIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNcontacto)
                    .addComponent(lblNnocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNrfc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNrazonsocial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNdireccionfiscal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNtelefono, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNcontraseña, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNnocliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(txtNrfc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNrazonsocial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNcontraseña)
                    .addComponent(txtNtelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNcontacto)
                    .addComponent(txtNdireccionfiscal))
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNnocliente)
                    .addComponent(txtNnocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrfc)
                    .addComponent(txtNrfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrazonsocial)
                    .addComponent(txtNrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNdireccionfiscal)
                    .addComponent(txtNdireccionfiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNcontacto)
                    .addComponent(txtNcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNtelefono)
                    .addComponent(txtNtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNcontraseña)
                    .addComponent(txtNcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try
        {
            String filePath = "C:\\Users\\Carlo\\OneDrive\\Escritorio\\Clientes.txt";
            FileWriter fw = new FileWriter(filePath, true);    
            String NoCliente = txtNnocliente.getText()+",";    
            fw.write(NoCliente);
            String rfc = txtNrfc.getText()+",";
            fw.write(rfc);
            String razonsocial = txtNrazonsocial.getText()+",";    
            fw.write(razonsocial);
            String dfiscal = txtNdireccionfiscal.getText()+",";    
            fw.write(dfiscal);
            String contacto = txtNcontacto.getText()+",";    
            fw.write(contacto);
            String tel = txtNtelefono.getText()+",";    
            fw.write(tel);
            String contra = txtNcontraseña.getText()+";";    
            fw.write(contra);
            fw.close();
            JOptionPane.showMessageDialog(null,"Registro realizado");
            AbarrotesPirata acceso = new AbarrotesPirata ();
                acceso.setVisible (true);
                this.setVisible (false);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNcontacto;
    private javax.swing.JLabel lblNcontraseña;
    private javax.swing.JLabel lblNdireccionfiscal;
    private javax.swing.JLabel lblNnocliente;
    private javax.swing.JLabel lblNrazonsocial;
    private javax.swing.JLabel lblNrfc;
    private javax.swing.JLabel lblNtelefono;
    private javax.swing.JTextField txtNcontacto;
    private javax.swing.JTextField txtNcontraseña;
    private javax.swing.JTextField txtNdireccionfiscal;
    private javax.swing.JTextField txtNnocliente;
    private javax.swing.JTextField txtNrazonsocial;
    private javax.swing.JTextField txtNrfc;
    private javax.swing.JTextField txtNtelefono;
    // End of variables declaration//GEN-END:variables

}