

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carlo
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }
    Archivos archivo = new Archivos ();
    String texto ="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReporteclientes = new javax.swing.JButton();
        btnReporteventas = new javax.swing.JButton();
        btnReporteproveedores = new javax.swing.JButton();
        btnReportefacturas = new javax.swing.JButton();
        btnReporteinventarios = new javax.swing.JButton();
        btnReporteganancias = new javax.swing.JButton();
        btnReportecompras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReporteclientes.setText("Reporte de Clientes");
        btnReporteclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteclientesActionPerformed(evt);
            }
        });

        btnReporteventas.setText("Reporte de Ventas");
        btnReporteventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteventasActionPerformed(evt);
            }
        });

        btnReporteproveedores.setText("Reporte de Proveedores");
        btnReporteproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteproveedoresActionPerformed(evt);
            }
        });

        btnReportefacturas.setText("Facturas");
        btnReportefacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportefacturasActionPerformed(evt);
            }
        });

        btnReporteinventarios.setText("Reporte de Inventarios");
        btnReporteinventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteinventariosActionPerformed(evt);
            }
        });

        btnReporteganancias.setText("Reporte de Ganancias");
        btnReporteganancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportegananciasActionPerformed(evt);
            }
        });

        btnReportecompras.setText("Reporte de Compras");
        btnReportecompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportecomprasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("REPORTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReportecompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReporteinventarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReporteclientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReporteproveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReportefacturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteventas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteganancias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteventas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportefacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteinventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteganancias, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnReportecompras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteclientesActionPerformed
        // TODO add your handling code here:
        String clientes = archivo.leerClientes("C:\\Users\\Carlo\\OneDrive\\Escritorio\\Clientes.txt");
        System.out.print(clientes);
    }//GEN-LAST:event_btnReporteclientesActionPerformed

    private void btnReporteproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteproveedoresActionPerformed
        // TODO add your handling code here:
        String proveedor = archivo.leerProveedor("C:\\Users\\Carlo\\OneDrive\\Escritorio\\Proveedores.txt");
        System.out.print(proveedor);
    }//GEN-LAST:event_btnReporteproveedoresActionPerformed

    private void btnReporteventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteventasActionPerformed
        // TODO add your handling code here:
        String venta = archivo.leerProveedor("C:\\Users\\Carlo\\OneDrive\\Escritorio\\ReporteVenta.txt");
        System.out.print(venta);
    }//GEN-LAST:event_btnReporteventasActionPerformed

    private void btnReportecomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportecomprasActionPerformed
        // TODO add your handling code here:
        String compra = archivo.leerProveedor("C:\\Users\\Carlo\\OneDrive\\Escritorio\\ReporteVenta.txt");
        System.out.print(compra);
    }//GEN-LAST:event_btnReportecomprasActionPerformed

    private void btnReporteinventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteinventariosActionPerformed
        // TODO add your handling code here:
        String inventario = archivo.leerInventario("C:\\Users\\Carlo\\OneDrive\\Escritorio\\Inventario.txt");
        System.out.print(inventario);
    }//GEN-LAST:event_btnReporteinventariosActionPerformed

    private void btnReportegananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportegananciasActionPerformed
        // TODO add your handling code here:
        archivo.leerGanancia();
    }//GEN-LAST:event_btnReportegananciasActionPerformed

    private void btnReportefacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportefacturasActionPerformed
        // TODO add your handling code here:
        String facturas = archivo.leerFacturas("C:\\Users\\Carlo\\OneDrive\\Escritorio\\Facturas.txt");
        System.out.print(facturas);
    }//GEN-LAST:event_btnReportefacturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteclientes;
    private javax.swing.JButton btnReportecompras;
    private javax.swing.JButton btnReportefacturas;
    private javax.swing.JButton btnReporteganancias;
    private javax.swing.JButton btnReporteinventarios;
    private javax.swing.JButton btnReporteproveedores;
    private javax.swing.JButton btnReporteventas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
